// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE24PSd38WmKLo_9YdYYJY2Izd4IZpRcg',
    appId: '1:757631834328:web:c9524b8add02acf4619fad',
    messagingSenderId: '757631834328',
    projectId: 'portfolio-9ad8a',
    authDomain: 'portfolio-9ad8a.firebaseapp.com',
    storageBucket: 'portfolio-9ad8a.appspot.com',
    measurementId: 'G-QYPF1V6GKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm4X7NT3P9Oda7kxRKlpFN3eH71qZklSg',
    appId: '1:757631834328:android:92df5c17e1876f7c619fad',
    messagingSenderId: '757631834328',
    projectId: 'portfolio-9ad8a',
    storageBucket: 'portfolio-9ad8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIW1KCUSjOek83yyI9GXMDMx_zxko4xVA',
    appId: '1:757631834328:ios:e34251d7e8007095619fad',
    messagingSenderId: '757631834328',
    projectId: 'portfolio-9ad8a',
    storageBucket: 'portfolio-9ad8a.appspot.com',
    iosBundleId: 'com.fakuraa.Portfolio',
  );
}
